datamend:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../data/insurance.duckdb"
      threads: 4
      schema: main
    sandbox:
      type: duckdb
      path: "../data/sandbox.duckdb"
      threads: 4
      schema: main
